export const SERVICE_IDENTIFIERS = {
    CONTAINER: Symbol("CONTAINER"),
    CUSTOMER_SERVICE: Symbol("CUSTOMER_SERVICE"),
    HTTP_CLIENT: Symbol("HTTP_CLIENT"),
    TOKEN_STORAGE: Symbol("TOKEN_STORAGE"),
};
